const resList = [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "199142",
        name: "Acs Chinese Flavour",
        uuid: "20350b46-0f67-459a-8741-9a3c08cd82ec",
        city: "7",
        area: "Taltala",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "bdxngpdzohlfvsnrfkmr",
        cuisines: ["Chinese"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 61,
        minDeliveryTime: 61,
        maxDeliveryTime: 61,
        slaString: "61 MINS",
        lastMileTravel: 2.5999999046325684,
        slugs: {
          restaurant: "acs-chinese-flavour-esplanade-esplanade",
          city: "kolkata",
        },
        cityState: "7",
        address: "8, Eliot Road, Taltala, Kolkata, West Bengal, India",
        locality: "Esplanade",
        parentId: 26894,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3000,
          message: "",
          title: "Delivery Charge",
          amount: "3000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7168984~p=1~eid=00000188-f884-eb92-13ab-af0c0053010d~srvts=1687796640658",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "15% OFF",
          subHeader: "UPTO ₹45",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "199142",
          deliveryTime: 61,
          minDeliveryTime: 61,
          maxDeliveryTime: 61,
          lastMileTravel: 2.5999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.9",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "101421",
        name: "Mughal Arsalan Biryani",
        uuid: "85307ece-3a0e-4595-bc37-485261ede304",
        city: "7",
        area: "College Square",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "dqryaxhlba4okzyzcx5z",
        cuisines: ["Indian", "Biryani"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        slaString: "25 MINS",
        lastMileTravel: 1.100000023841858,
        slugs: {
          restaurant: "mughal-arsalan-biryani-mg-road-burrabazar",
          city: "kolkata",
        },
        cityState: "7",
        address: "112 b mahatma gandhi road",
        locality: "MG road",
        parentId: 140901,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3000,
          message: "",
          title: "Delivery Charge",
          amount: "3000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.1 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹299",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "101421",
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          lastMileTravel: 1.100000023841858,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "278225",
        name: "AL Baik Fast Food Center",
        uuid: "a6fcccbc-adb9-491d-806e-0f6cf6a91a78",
        city: "7",
        area: "Barabazar Market",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "k3vuj7cncnfbwqqfkpbc",
        cuisines: ["Biryani", "Snacks", "North Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 51,
        minDeliveryTime: 51,
        maxDeliveryTime: 51,
        slaString: "51 MINS",
        lastMileTravel: 1,
        slugs: {
          restaurant: "al-baik-fast-food-center-burrabazar-burrabazar",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "54 PHEARS LANE GROUND FLOOR KOLKATA 700073 WARD 043 BR V, District - Kolkata, STATE - West Bengal - 700073",
        locality: "Burrabazar",
        parentId: 28935,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3000,
          message: "",
          title: "Delivery Charge",
          amount: "3000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹100 OFF",
          subHeader: "ABOVE ₹299",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "278225",
          deliveryTime: 51,
          minDeliveryTime: 51,
          maxDeliveryTime: 51,
          lastMileTravel: 1,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.7",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "38179",
        name: "Saima Restaurant - Mughlai and North Indian",
        uuid: "2bad85e8-9f86-4d47-a968-9d11fb619fff",
        city: "7",
        area: "Park Street Area",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "zsofs0ygzuhvez7k7926",
        cuisines: ["North Indian", "Mughlai", "Snacks"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 42,
        minDeliveryTime: 42,
        maxDeliveryTime: 42,
        slaString: "42 MINS",
        lastMileTravel: 3.5999999046325684,
        slugs: {
          restaurant: "saima-russel-street-central-kolkata",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "8/1A, Little Russel Street, Opposite Kenilworth Hotel, Russel Street, Kolkata",
        locality: "Opposite Kenilworth Hotel",
        parentId: 5566,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4000,
          message: "",
          title: "Delivery Charge",
          amount: "4000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7169171~p=4~eid=00000188-f884-eb92-13ab-af0d00530474~srvts=1687796640658",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "UPTO ₹40",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "38179",
          deliveryTime: 42,
          minDeliveryTime: 42,
          maxDeliveryTime: 42,
          lastMileTravel: 3.5999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "25140",
        name: "Zam Zam Restaurant",
        uuid: "069fd70e-07b7-4527-9f3a-d31f9a3e847d",
        city: "7",
        area: "Central Kolkata",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "e85899aceae5ebe729d0440e4b1239df",
        cuisines: ["Mughlai", "Biryani"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        slaString: "34 MINS",
        lastMileTravel: 2.9000000953674316,
        slugs: {
          restaurant: "zam-zam-park-circus-area-central-kolkata",
          city: "kolkata",
        },
        cityState: "7",
        address: "9/1, Noor Ali Avenue, Entally, Park Circus Area, Kolkata",
        locality: "Near Frank Anothony Public School",
        parentId: 8883,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3000,
          message: "",
          title: "Delivery Charge",
          amount: "3000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.9 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "25% OFF",
          subHeader: "UPTO ₹65",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "25140",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          lastMileTravel: 2.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.4",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "71260",
        name: "Lazeez Biryani",
        uuid: "ad04561e-9cc9-49d6-9789-7f96499d1edb",
        city: "7",
        area: "Entally",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "ja1bn8abcwoe4xjtxcz9",
        cuisines: ["Biryani", "Mughlai"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 21,
        minDeliveryTime: 21,
        maxDeliveryTime: 21,
        slaString: "21 MINS",
        lastMileTravel: 1.7999999523162842,
        slugs: {
          restaurant: "lazeez-biryani-park-circus-area-central-kolkata",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "1/A, Opposite Maulali Mazar, Convent Road, Park Circus Area, Kolkata",
        locality: " Maulali Dargah",
        parentId: 18798,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3000,
          message: "",
          title: "Delivery Charge",
          amount: "3000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.7 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "40% OFF",
          subHeader: "UPTO ₹80",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "71260",
          deliveryTime: 21,
          minDeliveryTime: 21,
          maxDeliveryTime: 21,
          lastMileTravel: 1.7999999523162842,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.6",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "552336",
        name: "Baskin Robbins - Ice Cream Desserts",
        uuid: "43c7035d-57ea-4ce6-830b-ee61aec974d9",
        city: "7",
        area: "BOROUGH-V",
        totalRatingsString: "50+ ratings",
        cloudinaryImageId: "126ea26268daed2437a1f243cb315ea8",
        cuisines: ["Desserts", "Ice Cream"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 45,
        minDeliveryTime: 45,
        maxDeliveryTime: 45,
        slaString: "45 MINS",
        lastMileTravel: 4,
        slugs: {
          restaurant: "baskin-robbins-borough-v-central-kolkata",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "5, GORKY TERRACE, BOROUGH-V 11 , KOLKATA MUNICIPAL CORPORATION, KOLKATA WEST BENGAL - 700017",
        locality: "GORKY TERRACE",
        parentId: 5588,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4000,
          message: "",
          title: "Delivery Charge",
          amount: "4000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7154666~p=28~eid=00000188-f884-eb92-13ab-af1500531c11~srvts=1687796640658",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "ABOVE ₹1000",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "552336",
          deliveryTime: 45,
          minDeliveryTime: 45,
          maxDeliveryTime: 45,
          lastMileTravel: 4,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 50,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "213121",
        name: "Wow! Momo",
        uuid: "b244c871-404b-4fdf-bcc8-e8a881925376",
        city: "7",
        area: "Burrabazar",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "90ac3da2963978f866177263fba805a7",
        cuisines: ["Tibetan", "Chinese", "Snacks", "Continental", "Desserts"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: "28 MINS",
        lastMileTravel: 1.2999999523162842,
        slugs: {
          restaurant: "wow-momo-ravindra-sarover-metro-jadavpur",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "Sealdah Railway Station,Concouse Area,Stall No -S10,Between Food Plaza And SBI ATM,Kolkata -700014",
        locality: "Sealdah Railway Station",
        parentId: 1776,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3000,
          message: "",
          title: "Delivery Charge",
          amount: "3000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹150 OFF",
          subHeader: "ABOVE ₹499",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "213121",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 1.2999999523162842,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "71267",
        name: "Red Chillies",
        uuid: "f3eabcd7-ee1e-4f9a-81c5-d883b3a91fc8",
        city: "7",
        area: "Kolkata",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "gdczdfpy2ylzhxfog1co",
        cuisines: ["Chinese"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: "30 MINS",
        lastMileTravel: 1.2999999523162842,
        slugs: {
          restaurant: "red-chilliz-gariahat-south-kolkata",
          city: "kolkata",
        },
        cityState: "7",
        address: "128,AJC Bose Road,Kolkata-700014",
        locality: "Gariahat",
        parentId: 168299,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3000,
          message: "",
          title: "Delivery Charge",
          amount: "3000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "71267",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 1.2999999523162842,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "368493",
        name: "Kwality Walls Frozen Dessert and Ice Cream Shop",
        uuid: "0f75070f-3624-435b-91c9-62d06d85492c",
        city: "7",
        area: "Sovabazar",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "onyi2eyuw9c4fqmw1q5z",
        cuisines: ["Desserts", "Ice Cream", "Ice Cream Cakes"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 2.299999952316284,
        slugs: {
          restaurant:
            "kwality-walls-frozen-dessert-and-ice-cream-shop-hatibagan-hatibagan-2",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "SHREYANSH: B/123/2/H/30,ACHARYA PRAFULLA CHANDRA ROAD, KOLKATA-700006,WARD-027,BR-IV,KOLKATA(W.B)-700006",
        locality: "Hatibagan",
        parentId: 582,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3200,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3200,
          message: "",
          title: "Delivery Charge",
          amount: "3200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7162547~p=13~eid=00000188-f884-eb92-13ab-af1000530d5d~srvts=1687796640658",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "368493",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 2.299999952316284,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.5",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "565580",
        name: "KFC",
        uuid: "4ca990e9-5688-4d3b-a17d-546eba016034",
        city: "7",
        area: "Sealdah",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "56c9ab92bd79745fd152a30fa2525426",
        cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 28,
        minDeliveryTime: 28,
        maxDeliveryTime: 28,
        slaString: "28 MINS",
        lastMileTravel: 1.2999999523162842,
        slugs: {
          restaurant: "kfc-sealdah-burrabazar",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "Sealdah Railway station, New Building complex , Ground floor- Platform no -14 Kolkata 700014",
        locality: "New Building complex",
        parentId: 547,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3200,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3200,
          message: "",
          title: "Delivery Charge",
          amount: "3200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "565580",
          deliveryTime: 28,
          minDeliveryTime: 28,
          maxDeliveryTime: 28,
          lastMileTravel: 1.2999999523162842,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "8698",
        name: "New Paul Dhaba",
        uuid: "5393a2c0-16ac-42b3-b2a1-5380856ca120",
        city: "7",
        area: "Maniktala",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "lelitcdusinvpdltscvu",
        cuisines: ["North Indian", "Chinese"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        slaString: "38 MINS",
        lastMileTravel: 2,
        slugs: {
          restaurant: "new-paul-dhaba-maniktala-hatibagan",
          city: "kolkata",
        },
        cityState: "7",
        address: "169, Vivekananda Road,Maniktala, Kolkata",
        locality: "Vivekananda Road",
        parentId: 658,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3000,
          message: "",
          title: "Delivery Charge",
          amount: "3000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "8698",
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          lastMileTravel: 2,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "208617",
        name: "Gupta Brothers The Abarkhabo Shoppe",
        uuid: "978024f6-9bda-48f1-a313-4979f8780062",
        city: "7",
        area: "MG Road",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "o6ahtv5y0sdtdo1b7gqt",
        cuisines: ["Indian"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 1.2999999523162842,
        slugs: {
          restaurant: "gupta-brothers-the-abarkhabo-shoppe-burrabazar-burrabazar",
          city: "kolkata",
        },
        cityState: "7",
        address:
          "161 CHITTARANJAN AVENUE,BESIDE M.G ROAD METRO,KOLKATA MUNICIPAL CORPORATION,KOLKATA,WEST BENGAL-700007",
        locality: "Burrabazar",
        parentId: 91646,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3000,
          message: "",
          title: "Delivery Charge",
          amount: "3000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "Closes soon",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "208617",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 1.2999999523162842,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.4",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "8587",
        name: "Royal Indian Hotel - Since 1905",
        uuid: "6c5ee6ee-f8dd-4c81-a9f9-1107cc80934e",
        city: "7",
        area: "Barabazar Market",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "oblqcc3ecvw4q9f7ukec",
        cuisines: ["North Indian", "Biryani", "Mughlai"],
        tags: [],
        costForTwo: 45000,
        costForTwoString: "₹450 FOR TWO",
        deliveryTime: 35,
        minDeliveryTime: 35,
        maxDeliveryTime: 35,
        slaString: "35 MINS",
        lastMileTravel: 1.5,
        slugs: {
          restaurant: "royal-indian-hotel-rabindra-sarani-burrabazar",
          city: "kolkata",
        },
        cityState: "7",
        address: "147, Rabindra Sarani, Bara Bazar, Kolkata",
        locality: "Rabindra Sarani",
        parentId: 1735,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3000,
          message: "",
          title: "Delivery Charge",
          amount: "3000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "8587",
          deliveryTime: 35,
          minDeliveryTime: 35,
          maxDeliveryTime: 35,
          lastMileTravel: 1.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.4",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "95963",
        name: "Hot Wok",
        uuid: "f9429ee8-19a0-4bdd-a731-7ec5dd722fe6",
        city: "7",
        area: "Tangra",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "tqs5jlopsbl29rdi07vt",
        cuisines: ["Indian", "Chinese"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 45,
        minDeliveryTime: 45,
        maxDeliveryTime: 45,
        slaString: "45 MINS",
        lastMileTravel: 4.5,
        slugs: {
          restaurant: "hot-wok-kolkata-dummy-inbound-area",
          city: "kolkata",
        },
        cityState: "7",
        address: "56, MATHESWARTALA ROAD, KOLKATA",
        locality: "TANGRA CHINA TOWN",
        parentId: 4142,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4000,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4000,
          message: "",
          title: "Delivery Charge",
          amount: "4000",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7114098~p=16~eid=00000188-f884-eb92-13ab-af110053104a~srvts=1687796640658",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "95963",
          deliveryTime: 45,
          minDeliveryTime: 45,
          maxDeliveryTime: 45,
          lastMileTravel: 4.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.4",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
  ];



  export default resList;